# Generated by Django 4.1.7 on 2023-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_column='rut', max_length=20)),
                ('nombre', models.CharField(db_column='nombre', max_length=20)),
                ('apellido', models.CharField(db_column='apellido', max_length=30)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
    ]
